/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import javax.swing.*;

/**
 *
 * @author ROBERTO
 */
public class CuadroTexto extends javax.swing.JPanel {

    /**
     * Creates new form CuadroTexto
     */
    public CuadroTexto(String texto, String personaje, ImageIcon imagen) {
        initComponents(texto, personaje, imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String texto, String personaje, ImageIcon imagen) {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        setOpaque(false);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(null);

        jLabel3.setText(personaje);
        jLabel3.setBounds(20, 10, 130, 30);
        jPanel1.add(jLabel3);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(texto);
        jTextArea1.setOpaque(false);
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.setBounds(40, 40, 890, 140);
          jScrollPane1.setOpaque(true);
         jPanel1.add(jScrollPane1);

        jPanel1.setBounds(30, 290, 950, 190);
        add(jPanel1);

        jLabel2.setBounds(640, 0, 850, 960);
        jLabel2.setIcon(imagen);
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
