/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Dialogo;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author ROBERTO
 */
public class Entrada extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Entrada.class.getName());
private Dimension tamPant;
private  ArrayList<Dialogo> dialogosTuto;
private int dialogoActual;

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        tamPant = Toolkit.getDefaultToolkit().getScreenSize();
        dialogosTuto= new ArrayList<Dialogo>();
        dialogoActual=0;
        crearDialogos();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        cajaTexto  = new JPanel();
        try {
            BufferedImage imagen = ImageIO.read(new File("DatosAuxiliares/Escenarios/entrada por afuera.jpg"));

            jLabel1 = new JLabel();
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            setMinimumSize(tamPant);
            setUndecorated(true);
            setPreferredSize(tamPant);
            getContentPane().setLayout(null);
            ImageIcon icono = new ImageIcon(imagen.getScaledInstance(tamPant.width, tamPant.height, Image.SCALE_SMOOTH));
            jLabel1.setIcon(icono); // NOI18N
            jLabel1.setFocusable(false);
            jLabel1.setMaximumSize(tamPant);
            jLabel1.setMinimumSize(tamPant);
            jLabel1.setPreferredSize(tamPant);
            jLabel1.setBounds(0, 0, tamPant.width, tamPant.height);

            cajaTexto.setOpaque(false);
            cajaTexto.setBounds(220, 280, 1200, 800);
            cajaTexto.setLayout(null);
            ponerDialogo();
            getContentPane().add(cajaTexto);


            getContentPane().add(jLabel1);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }



        pack();
    }// </editor-fold>//GEN-END:initComponents
public void ponerDialogo() {
        if(dialogoActual < dialogosTuto.size()) {
             Dialogo aux = dialogosTuto.get(dialogoActual);
             CuadroTexto cT = new CuadroTexto(aux.getTexto(), aux.getPersonaje(), aux.getIcono());
            cT.setBounds(0, 0, 1100, 700);

            cT.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cTMouseClicked(evt);
                }
            });
            dialogoActual++;
            cajaTexto.removeAll();
            cajaTexto.add(cT);
        }else {
            cajaTexto.removeAll();
        }

    }

    private void cTMouseClicked(MouseEvent evt) {
        ponerDialogo();
        getContentPane().revalidate();
        getContentPane().repaint();
    }


    public void crearDialogos(){

    ImageIcon policia = new ImageIcon("DatosAuxiliares/NPC/Policia.png");
        ImageIcon dueno = new ImageIcon("DatosAuxiliares/NPC/Dueño.png");
        ImageIcon secretaria  = new ImageIcon("DatosAuxiliares/NPC/Secretaria.png");
    Dialogo d1= new Dialogo("Hola. Como estas.", "Policia", policia );
    Dialogo d2= new Dialogo("Espero que hayas dormido bien.", "Policia", policia );
    Dialogo d3= new Dialogo("Tenemos trabajo que hacer.", "Policia", policia );
    Dialogo d4= new Dialogo("Este parece ser un caso bastante serio.", "Policia", policia );
    Dialogo d5= new Dialogo("No se alarme oficial. El caso esta practicamente resuelto.", "Dueño", dueno );
    Dialogo d6= new Dialogo("Simplemente no pudo aguantar el estres laboral.", "Dueño", dueno );
    Dialogo d7= new Dialogo("Por favor señor, hasta que el detective diga lo contrario el caso seguira abierto.", "Policia", policia );
    Dialogo d8= new Dialogo("Como diga.", "Dueño", dueno );
    Dialogo d9= new Dialogo("Buenas.", "Secretaria", secretaria );
    dialogosTuto.add(d1);
    dialogosTuto.add(d2);
    dialogosTuto.add(d3);
    dialogosTuto.add(d4);
        dialogosTuto.add(d5);
        dialogosTuto.add(d6);
        dialogosTuto.add(d7);
        dialogosTuto.add(d8);
        dialogosTuto.add(d9);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Entrada().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel cajaTexto;
    // End of variables declaration//GEN-END:variables
}
