package Interfaz.Menu;




import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;

import Logica.Reproductor;

/**
 *
 * @author ROBERTO
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private Dimension tamPant;
    private Timer timer;
    private TimerTask tarea;
    int largoBot;
    int anchoBot;
    int xBot;
    private static boolean  evitarRepetir = false;
    /**
     * Creates new form Menu1
     */
    public Menu() 
    {
        if(!evitarRepetir)
        {
            Reproductor reproductor = Reproductor.getInstancia();
            reproductor.iniciarMusica();
            evitarRepetir = true;
        }
        timer = new Timer();
        tarea = new TimerTask() {
            @Override
            public void run() {
                dispose();
            }
        };
        
        tamPant = Toolkit.getDefaultToolkit().getScreenSize();
        largoBot = (int) (tamPant.getWidth()*0.2);
        anchoBot = (int) (tamPant.getHeight()*0.07);
        xBot = (int) (tamPant.getWidth()*0.07);
        initComponents();
        
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        botonNuevPart = new javax.swing.JButton();
        botonCargPar = new javax.swing.JButton();
        botonOpc = new javax.swing.JButton();
        botonCreditos = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detective");
        setMinimumSize(new java.awt.Dimension(1600, 930));
        setUndecorated(true);
        getContentPane().setLayout(null);

        botonSalir.setFont(new java.awt.Font("Segoe UI", 0, (int)(largoBot*0.13)));
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setFocusPainted(false);
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        botonSalir.setBounds(xBot,(int) (tamPant.getHeight()*0.86), largoBot, anchoBot);
        getContentPane().add(botonSalir);

        botonNuevPart.setFont(new java.awt.Font("Segoe UI", 0, (int)(largoBot*0.13)));
        botonNuevPart.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevPart.setText("Nueva Partida");
        botonNuevPart.setBorderPainted(false);
        botonNuevPart.setContentAreaFilled(false);
        botonNuevPart.setFocusPainted(false);
        botonNuevPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonNuevPartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonNuevPartMouseExited(evt);
            }
        });
        botonNuevPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevPartActionPerformed(evt);
            }
        });
        botonNuevPart.setBounds(xBot,(int) (tamPant.getHeight()*0.54), largoBot, anchoBot);
        getContentPane().add(botonNuevPart);

        botonCargPar.setFont(new java.awt.Font("Segoe UI", 0, (int)(largoBot*0.13)));
        botonCargPar.setForeground(new java.awt.Color(255, 255, 255));
        botonCargPar.setText("Cargar Partida");
        botonCargPar.setBorderPainted(false);
        botonCargPar.setContentAreaFilled(false);
        botonCargPar.setFocusPainted(false);
        botonCargPar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargParMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargParMouseExited(evt);
            }
        });
        botonCargPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargParActionPerformed(evt);
            }
        });
        botonCargPar.setBounds(xBot,(int) (tamPant.getHeight()*0.62), largoBot, anchoBot);
        getContentPane().add(botonCargPar);

        botonOpc.setFont(new java.awt.Font("Segoe UI", 0, (int)(largoBot*0.13)));
        botonOpc.setForeground(new java.awt.Color(255, 255, 255));
        botonOpc.setText("Opciones");
        botonOpc.setBorderPainted(false);
        botonOpc.setContentAreaFilled(false);
        botonOpc.setFocusPainted(false);
        botonOpc.setBounds(xBot,(int) (tamPant.getHeight()*0.70), largoBot, anchoBot);
        botonOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonOpcMouseExited(evt);
            }
        });
        botonOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcActionPerformed(evt);
            }
        });
        getContentPane().add(botonOpc);

        botonCreditos.setFont(new java.awt.Font("Segoe UI", 0, (int)(largoBot*0.13)));
        botonCreditos.setForeground(new java.awt.Color(255, 255, 255));
        botonCreditos.setText("Creditos");
        botonCreditos.setBorderPainted(false);
        botonCreditos.setContentAreaFilled(false);
        botonCreditos.setFocusPainted(false);
        botonCreditos.setBounds(xBot,(int) (tamPant.getHeight()*0.78), largoBot, anchoBot);
        botonCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCreditosMouseExited(evt);
            }
        });
        botonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(botonCreditos);

        fondo.setFont(new java.awt.Font("Script MT Bold", 1, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon("DatosAuxiliares/Fondo presentacion.jpeg\\")); // NOI18N
        fondo.setText("jLabel1");
        fondo.setMaximumSize(tamPant);
        fondo.setMinimumSize(tamPant);
        fondo.setPreferredSize(tamPant);
        fondo.setBounds(0,0, tamPant.width, tamPant.height );
        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int salir= JOptionPane.showConfirmDialog(null,"Estas seguro de queres salir del juego", "", JOptionPane.YES_NO_OPTION);
        if(salir==0)
            System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonNuevPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevPartActionPerformed

        NuevaPartida nP = new NuevaPartida();
        nP.setVisible(true);
       timer.schedule(tarea, 1000);
    }

    private void botonCargParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargParActionPerformed
       CargarPartida cP = new CargarPartida();

       cP.setVisible(true);
        timer.schedule(tarea, 1000);

    }//GEN-LAST:event_botonCargParActionPerformed

    private void botonOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcActionPerformed
      Opciones opc = new Opciones();

      opc.setVisible(true);
        timer.schedule(tarea, 1000);
    }//GEN-LAST:event_botonOpcActionPerformed

    private void botonNuevPartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevPartMouseEntered
        botonNuevPart.setForeground(Color.red);
    }//GEN-LAST:event_botonNuevPartMouseEntered

    private void botonNuevPartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevPartMouseExited
          botonNuevPart.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_botonNuevPartMouseExited

    private void botonCargParMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargParMouseEntered
        botonCargPar.setForeground(Color.red);
    }//GEN-LAST:event_botonCargParMouseEntered

    private void botonCargParMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargParMouseExited
       botonCargPar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_botonCargParMouseExited

    private void botonOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOpcMouseEntered
          botonOpc.setForeground(Color.red);
    }//GEN-LAST:event_botonOpcMouseEntered

    private void botonOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOpcMouseExited
       botonOpc.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_botonOpcMouseExited

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        botonSalir.setForeground(Color.red);
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
         botonSalir.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCreditosMouseEntered
        botonCreditos.setForeground(Color.red);
    }//GEN-LAST:event_botonCreditosMouseEntered

    private void botonCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCreditosMouseExited
       botonCreditos.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_botonCreditosMouseExited

    private void botonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreditosActionPerformed
        Creditos cre = new Creditos();
        cre.setVisible(true);
        timer.schedule(tarea, 1000);
    }//GEN-LAST:event_botonCreditosActionPerformed

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargPar;
    private javax.swing.JButton botonCreditos;
    private javax.swing.JButton botonNuevPart;
    private javax.swing.JButton botonOpc;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}

