/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaz.InterfazJugador;

import Interfaz.Menu.MenuPrincipal;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ROBERTO
 */
public class MenuInterno extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInterno.class.getName());
    private Dimension tamPant;

    private Timer timer;
    private TimerTask tarea;

    /**
     * Creates new form MenuInterno
     */
    public MenuInterno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        tamPant = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();

        timer = new Timer();
        tarea = new TimerTask() {
            @Override
            public void run() {
                dispose();
            }
        };

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        fondo = new JLabel();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        setBackground(new Color(0, 0,0,75 ));

        jPanel1.setBackground(Color.black);
        jPanel1.setLayout(null);

        jButton1.setText("Continuar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFont(new Font("Segoe UI", 0, (int)(tamPant.height*0.04)));
        jButton1.setForeground(Color.white);
        jButton1.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds((int) (tamPant.width*0.05), (int) (tamPant.height*0.20),(int) (tamPant.width*0.3), (int) (tamPant.height*0.065));
        jPanel1.add(jButton1);

        jButton2.setText("Opciones");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFont(new Font("Segoe UI", 0, (int)(tamPant.height*0.04)));
        jButton2.setForeground(Color.white);
        jButton2.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds((int) (tamPant.width*0.05), (int) (tamPant.height*0.28),(int) (tamPant.width*0.3), (int) (tamPant.height*0.065));
        jPanel1.add(jButton2);

        jButton3.setText("Guardar Partida");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFont(new Font("Segoe UI", 0, (int)(tamPant.height*0.04)));
        jButton3.setForeground(Color.white);
        jButton3.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds((int) (tamPant.width*0.05), (int) (tamPant.height*0.36),(int) (tamPant.width*0.3), (int) (tamPant.height*0.065));
        jPanel1.add(jButton3);

        jButton4.setText("Salir al Menu");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFont(new Font("Segoe UI", 0, (int)(tamPant.height*0.04)));
        jButton4.setForeground(Color.white);
        jButton4.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds((int) (tamPant.width*0.05), (int) (tamPant.height*0.44),(int) (tamPant.width*0.3), (int) (tamPant.height*0.065));
        jPanel1.add(jButton4);

        jButton5.setText("Salir al Escritorio");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFont(new Font("Segoe UI", 0, (int)(tamPant.height*0.04)));
        jButton5.setForeground(Color.white);

        jButton5.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds((int) (tamPant.width*0.05), (int) (tamPant.height*0.52),(int) (tamPant.width*0.3), (int) (tamPant.height*0.065));
        jPanel1.add(jButton5);
        jPanel1.setBounds((int) (tamPant.width*0.3), (int) (tamPant.height*0.2), (int) (tamPant.width*0.4), (int) (tamPant.height*0.65));

        BufferedImage imagen = null;

        try {
            imagen = ImageIO.read(new File("DatosAuxiliares/OjetosInterfaz/menu 1.jpg"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        ImageIcon icono = new ImageIcon(imagen.getScaledInstance((int) (tamPant.width*0.4), (int) (tamPant.height*0.65), Image.SCALE_SMOOTH));
        fondo.setIcon(icono);
        fondo.setBounds(0, 0, (int) (tamPant.width*0.4), (int) (tamPant.height*0.65));
        jPanel1.add(fondo);
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose();
    }

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {
        jButton1.setForeground(Color.red);
    }

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
        jButton1.setForeground(Color.white);
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {
        jButton2.setForeground(Color.red);
    }

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {
        jButton2.setForeground(Color.white);
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {
        jButton3.setForeground(Color.red);
    }

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {
        jButton3.setForeground(Color.white);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        int salir= JOptionPane.showConfirmDialog(null,"Estas seguro de querer salir al menu principal", "", JOptionPane.YES_NO_OPTION);
        if(salir==0) {
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
           dispose();


        }

    }

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {
        jButton4.setForeground(Color.red);
    }

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {
        jButton4.setForeground(Color.white);
    }


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        int salir= JOptionPane.showConfirmDialog(null,"Estas seguro de querer salir del juego", "", JOptionPane.YES_NO_OPTION);
        if(salir==0)
            System.exit(0);
    }

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {
        jButton5.setForeground(Color.red);
    }

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {
        jButton5.setForeground(Color.white);
    }










    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuInterno dialog = new MenuInterno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel fondo;
    // End of variables declaration
}
